# Generated by Django 2.2.7 on 2019-12-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_accountemailaddress_accountemailconfirmation_authgroup_authgrouppermissions_authpermission_djangoadm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('access_new_hire', 'Access to New Hire link'), ('access_on-boarding', 'Access to On-boarding link'), ('access_benefits', 'Access to Benefits link')),
                'managed': False,
            },
        ),
    ]
