# Generated by Django 2.2.7 on 2019-12-01 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_links'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={'managed': False, 'permissions': (('accessto_manage_user_accounts', 'Access to Manage User Accounts link'), ('accessto_assign_roles', 'Access to Assign Roles link'), ('accessto_help_desk', 'Access to Help Desk link'), ('accessto_finance_reports', 'Access to Finance Reports link'), ('accessto_accounts_payable', 'Access to Accounts Payable link'), ('accessto_accounts_receivable', 'Access to Accounts Receivable link'), ('accessto_tax', 'Access to Tax link'), ('accessto_sales_reports', 'Access to Sales Reports link'), ('accessto_sales_leads', 'Access to Sales Leads link'), ('accessto_sales_demo', 'Access to Sales Demo link'), ('accessto_new_hire', 'Access to New Hire link'), ('accessto_on-boarding', 'Access to On-boarding link'), ('accessto_benefits', 'Access to Benefits link'), ('accessto_payroll', 'Access to Payroll link'), ('accessto_Terminations', 'Access to Terminations link'), ('accessto_hr_reports', 'Access to HR Reports link'), ('accessto_application_monitoring', 'Access to Application Monitoring link'), ('accessto_tech_support', 'Access to Tech Support link'), ('accessto_app_development', 'Access to App Development link'), ('accessto_app_admin', 'Access to App Admin link'), ('accessto_release_management', 'Access to Release Management link'))},
        ),
    ]
